### ISSUE TITLE
Preconfiguration params bug

### ISSUE THREAD

**Issue by jorgealbertojc** [voilab/angular-qtip2#1]
while load the directive this error is shown:

``` javascript
Uncaught TypeError: Cannot read prope ty 'module' of undefined
```

I will fork the directive to correct the problem and work with it ... thanks :smile:

![selection_002](https://cloud.githubusercontent.com/assets/219255/9839051/3862196e-5a33-11e5-940b-59ee11605b01.png)

**Comment by karamasoff** [comment]
Ouch :P
I always used it as an amd package. I published a fixed version.

**Comment by jorgealbertojc** [comment]
thanks :smile:
